using System;
using System.IO;
using System.Reflection;
using Server;
using Server.Accounting;
using Server.Mobiles;
using Server.Items;
using Server.Spells;
using Server.Spells.Necromancy;
using Server.Spells.Spellweaving;
using Server.HavenPrototype;
public static class CasterSmoke {
 static void Check(bool ok,string name){if(!ok)throw new Exception(name);File.AppendAllText("caster-checks.log","PASS "+name+"\n");}
 public static void Initialize(){if(File.Exists("CASTER-TEST-ONLY"))EventSink.ServerStarted+=()=>Timer.DelayCall(TimeSpan.FromSeconds(4),Run);}
 static void Run(){try{var p=new PlayerMobile{Player=true,Name="Caster fixture",Body=0x190,RawStr=200};p.AddItem(new Backpack());new Account("caster-"+Guid.NewGuid().ToString("N").Substring(0,8),Guid.NewGuid().ToString("N"))[0]=p;p.MoveToWorld(new Point3D(1015,527,-65),Map.Malas);var c=HavenCompanion.Claim(p);Check(c.SetRole(p,CompanionRole.Caster),"caster role selected");Check(c.Skills.Spellweaving.Base>=100&&c.Skills.Necromancy.Base>=100&&c.Skills.SpiritSpeak.Base>=100,"caster starts with spellweaving and necromancy skills");var book=c.FindItemOnLayer(Layer.OneHanded) as Spellbook;Check(book!=null&&book.Attributes.CastSpeed==2&&book.Attributes.CastRecovery==6,"caster receives faster casting grimoire");Check(c.MaintainSpellweaver(),"native Wraith Form begins casting");Timer.DelayCall(TimeSpan.FromSeconds(6),()=>Finish(p,c));}catch(Exception e){File.AppendAllText("caster-checks.log","FAIL "+e+"\n");Core.Kill(false);}}
 static void Finish(PlayerMobile p,HavenCompanion c){try{var context=TransformationSpellHelper.GetContext(c);Check(context!=null&&context.Type==typeof(WraithFormSpell),"native Wraith Form becomes active");var victim=new Ogre();victim.MoveToWorld(p.Location,p.Map);victim.ManaMaxSeed=200;victim.Mana=100;c.Mana=20;AOS.DoLeech(100,c,victim);Check(c.Mana==40&&victim.Mana==80,"native Wraith mana drain replenishes companion");c.Mana=100;victim.Hits=1;var ai=c.AIObject as HavenCompanionMageAI;var spell=ai.ChooseSpell(victim);Check(spell is WordOfDeathSpell,"caster chooses Spellweaving finisher");Check(!ai.SmartAI,"random native combat teleport disabled");var due=(DateTime)typeof(HavenCompanionMageAI).GetMethod("GetCastDelay",BindingFlags.Instance|BindingFlags.NonPublic).Invoke(ai,new object[]{spell});Check(due-DateTime.UtcNow<=spell.GetCastDelay()+spell.GetCastRecovery()+TimeSpan.FromSeconds(0.15),"only short scheduling pause added to native spell timing");Check(c.SetRole(p,CompanionRole.Warrior),"can switch back to warrior");c.MaintainSpellweaver();Check(TransformationSpellHelper.GetContext(c)==null,"leaving caster removes Wraith Form");var wallet=new HavenWallet(p);p.Backpack.DropItem(wallet);var rewards=new Bag();p.Backpack.DropItem(rewards);var check=new BankCheck(10000);rewards.DropItem(check);var gold=new Gold(25);p.Backpack.DropItem(gold);long bank=wallet.Balance;wallet.OnDoubleClick(p);Check(check.Deleted&&gold.Deleted&&wallet.Balance==bank+10025,"wallet double click deposits mini champ check and gold exactly once");wallet.OnDoubleClick(p);Check(wallet.Balance==bank+10025,"reopening wallet cannot duplicate deposited checks");var bear=new BrownBear();bear.MoveToWorld(p.Location,p.Map);bear.SetControlMaster(p);bear.IsBonded=true;bear.Kill();Check(bear.IsDeadPet&&c.SupportPatient(bear)&&!bear.IsDeadPet,"companion can resurrect owner bonded pet");bear.Delete();victim.Delete();c.Delete();p.Delete();File.AppendAllText("caster-checks.log","COMPLETE\n");Core.Kill(false);}catch(Exception e){File.AppendAllText("caster-checks.log","FAIL "+e+"\n");Core.Kill(false);}}
}
