using System;
using System.Linq;
using System.IO;
using Server;
using Server.Items;
using Server.Mobiles;
using Server.Accounting;
using Server.HavenPrototype;
public static class CompanionInventorySmoke {
 public static void Initialize(){if(File.Exists("INVENTORY-TEST-ONLY"))EventSink.ServerStarted+=()=>Timer.DelayCall(TimeSpan.FromSeconds(3),Run);}
 static void Check(bool ok,string label){if(!ok)throw new Exception(label);File.AppendAllText("inventory-checks.log","PASS "+label+"\n");}
 static void Run(){try{
 foreach(var whirlwind in new BaseWeapon[]{new HavenCycloneAxe(),new HavenTempestStaff(),new HavenCycloneScimitar(),new HavenCycloneMace(),new HavenCycloneKryss()}){
  Check(whirlwind.PrimaryAbility==WeaponAbility.WhirlwindAttack||whirlwind.SecondaryAbility==WeaponAbility.WhirlwindAttack,"leveling whirlwind weapon exposes native special move");
  var progression=HavenAdvancedGear.Find(whirlwind);Check(progression!=null&&HavenAdvancedGear.AutoKind(whirlwind)==6,"whirlwind progression survives equipment recognition");
  progression.Gain(1900);Check(progression.Level==20&&progression.Experience==1900&&whirlwind.WeaponAttributes.HitLeechMana>30,"whirlwind weapon levels and grows mana leech");
  Check(whirlwind.WeaponAttributes.HitFireArea==0&&whirlwind.WeaponAttributes.HitColdArea==0&&whirlwind.WeaponAttributes.HitEnergyArea==0,"whirlwind weapon uses active special rather than elemental proc");progression.Delete();whirlwind.Delete();
 }
 Check(HavenCompanionProgression.TamingTraining(500,5,0.99)==50,"five minute early tame training gives five points");
 Check(HavenCompanionProgression.TamingTraining(1000,5,0.99)==10,"normal training above100");
 Check(HavenCompanionProgression.TamingTraining(1200,5,0.99)==0,"over120 remains twenty times slower");
 var owner=new MissionSafetyPlayer{Player=true,Body=0x190};owner.AddItem(new Backpack());new Account("inventory-"+Guid.NewGuid().ToString("N"),Guid.NewGuid().ToString("N"))[0]=owner;owner.MoveToWorld(new Point3D(1015,527,-65),Map.Malas);
 Check(HavenResources.Types.Length==HavenResources.Names.Length,"resource catalog names match stable IDs");
 var shipLedger=new HavenResourceLedger();var shipTarget=new HavenResourceLedger();owner.Backpack.DropItem(shipLedger);owner.Backpack.DropItem(shipTarget);
 foreach(var ammoType in new[]{typeof(Cannonball),typeof(Grapeshot),typeof(PowderCharge),typeof(FuseCord)}){int id=Array.IndexOf(HavenResources.Types,ammoType);var ammo=HavenResources.Create(id,25);Check(ammo!=null&&ammo.GetType()==ammoType&&ammo.Amount==25,"native ship resource creation "+ammoType.Name);owner.Backpack.DropItem(ammo);Check(shipLedger.Absorb(owner,ammo)==1&&ammo.Deleted&&shipLedger.Balance(id)==25,"ship supply ledger deposit "+ammoType.Name);Check(shipLedger.TransferAll(owner,shipTarget)&&shipTarget.Balance(id)==25,"ship supply ledger transfer "+ammoType.Name);Check(shipTarget.Withdraw(owner,id,25,false)&&shipTarget.Balance(id)==0,"ship supply ledger withdrawal "+ammoType.Name);foreach(var withdrawn in owner.Backpack.FindItemsByType(ammoType,true))withdrawn.Delete();}
 shipLedger.Delete();shipTarget.Delete();
 double[] rarityRolls={.59,.60,.85,.95,.99};string[] rarityNames={"Common","Uncommon","Rare","Epic","Legendary"};
 for(int tier=0;tier<5;tier++)for(int role=0;role<7;role++)for(int style=0;style<10;style++){var cloth=HavenWorldDiscoveries.Clothing(rarityRolls[tier],role,style);Check(cloth.Name.StartsWith(rarityNames[tier]+" "),"world clothing rarity "+tier+" role "+role+" style "+style);var progress=HavenAdvancedGear.Find(cloth);Check((progress!=null)==(tier==4),"only original legendary clothing levels");if(progress!=null){progress.Gain(1900);int luck=cloth.Attributes.Luck;progress.Apply();Check(progress.Level==20&&cloth.Attributes.Luck==luck,"legendary clothing caps and reapplies without stacking");progress.Delete();}cloth.Delete();}
 var discoveryFoe=new Horse();discoveryFoe.MoveToWorld(owner.Location,owner.Map);Check(HavenWorldDiscoveries.Award(discoveryFoe,owner,.002),"ordinary world kill can drop clothing without boss requirements");Check(!HavenWorldDiscoveries.Award(discoveryFoe,owner,.002),"world clothing cannot roll twice for same kill and player");discoveryFoe.Delete();
 owner.MoveToWorld(new Point3D(3500,2580,14),Map.Trammel);var fastSkill=owner.Skills.Mining;fastSkill.Cap=120;fastSkill.Base=110;Check(HavenNewcomerBonus.Chance(owner,fastSkill)==5&&HavenNewcomerBonus.Amount(owner,fastSkill,1)==5,"free skill trains five times faster above100 inside Haven");fastSkill.Base=119.9;Check(HavenNewcomerBonus.Amount(owner,fastSkill,1)==1,"free skill bonus stops exactly at120");fastSkill.Base=120;Check(HavenNewcomerBonus.Chance(owner,fastSkill)==1,"no accelerated gains past120");fastSkill.Base=104.9;fastSkill.Cap=105;Check(HavenNewcomerBonus.Amount(owner,fastSkill,1)==1,"Haven bonus respects lower individual cap");var combatSkill=owner.Skills.Swords;combatSkill.Cap=120;combatSkill.Base=110;Check(HavenNewcomerBonus.Chance(owner,combatSkill)==1,"nonfree skills retain100 accelerated threshold");owner.MoveToWorld(new Point3D(1015,527,-65),Map.Malas);fastSkill.Cap=120;fastSkill.Base=110;Check(HavenNewcomerBonus.Chance(owner,fastSkill)==1&&HavenNewcomerBonus.Amount(owner,fastSkill,1)==1,"free skill training outside Haven unchanged");
 owner.Criminal=true;Check(HavenPreview.CanTravel(owner),"criminal status alone does not block Haven travel");Check(owner.Criminal,"travel eligibility preserves criminal status");
 var opponent=new Horse();opponent.MoveToWorld(owner.Location,owner.Map);owner.Combatant=opponent;Check(!HavenPreview.CanTravel(owner),"active combat blocks Haven travel");owner.Combatant=null;owner.Aggressors.Clear();owner.Aggressed.Clear();
 var incoming=AggressorInfo.Create(opponent,owner,false);owner.Aggressors.Add(incoming);Check(!HavenPreview.CanTravel(owner),"recent incoming combat blocks Haven travel");typeof(AggressorInfo).GetField("m_LastCombatTime",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).SetValue(incoming,DateTime.UtcNow.AddSeconds(-16));Check(HavenPreview.CanTravel(owner),"Haven travel unlocks after fifteen seconds while native aggression remains");Check(!incoming.Expired,"short travel cooldown preserves native aggression record");incoming.Refresh();Check(!HavenPreview.CanTravel(owner),"new attack restarts fifteen second travel cooldown");owner.Aggressors.Remove(incoming);
 var outgoing=AggressorInfo.Create(owner,opponent,false);owner.Aggressed.Add(outgoing);Check(!HavenPreview.CanTravel(owner),"recent outgoing combat blocks Haven travel");owner.Aggressed.Remove(outgoing);
 Check(HavenPreview.CanTravel(owner),"travel resumes when combat clears even while criminal");owner.Criminal=false;opponent.Delete();
 var home=HavenStarterHome.Claim(owner);Check(home!=null,"create owned home for travel check");
 var homeEnemy=new Horse();homeEnemy.MoveToWorld(owner.Location,owner.Map);owner.Combatant=homeEnemy;owner.Criminal=true;
 Check(HavenStarterHome.Travel(owner),"home travel works during combat while criminal");Check(owner.Criminal,"home does not erase criminal status");Check(owner.Map==home.Map&&owner.InRange(home,8),"home travel reaches owned lodge");
 owner.Combatant=null;owner.Aggressors.Clear();owner.Aggressed.Clear();owner.Criminal=false;homeEnemy.Delete();home.Delete();owner.MoveToWorld(new Point3D(1015,527,-65),Map.Malas);
 owner.Criminal=true;Check(Server.Spells.SpellHelper.CheckCanTravel(owner),"native travel helper permits criminal-only travel");var gate=new PublicMoongate();Check(gate.CanUseGate(owner,false),"public moongate permits criminal-only travel");gate.Delete();owner.Criminal=false;
 var trash=new HavenTrashBag();owner.Backpack.DropItem(trash);var scrap=new Katana();scrap.Attributes.WeaponDamage=20;scrap.WeaponAttributes.HitLeechHits=50;scrap.WeaponAttributes.HitLeechMana=50;double value=Server.Engines.Points.CleanUpBritanniaData.GetPoints(scrap);Check(value>0,"scrap has native CUB value");double balance=Server.Engines.Points.PointsSystem.CleanUpBritannia.GetPoints(owner);
 Check(trash.OnDragDrop(owner,scrap),"trash accepts eligible scrap");Check(Server.Engines.Points.PointsSystem.CleanUpBritannia.GetPoints(owner)==balance,"no CUB credit before disposal");owner.Backpack.DropItem(scrap);trash.Empty(501479);Check(Server.Engines.Points.PointsSystem.CleanUpBritannia.GetPoints(owner)==balance,"retrieved trash earns no points");
 Check(trash.OnDragDrop(owner,scrap),"retrieved item can be discarded again");using(var stream=new MemoryStream()){var writer=new BinaryFileWriter(stream,true);trash.WritePendingCleanup(writer);writer.Flush();trash.m_Cleanup.Clear();stream.Position=0;trash.ReadPendingCleanup(new BinaryFileReader(new BinaryReader(stream)));}Check(trash.m_Cleanup.Count==1,"pending CUB ownership and value survive serialization");trash.Empty(501479);Check(Server.Engines.Points.PointsSystem.CleanUpBritannia.GetPoints(owner)==balance+value,"disposed trash earns native CUB points once");trash.Empty(501479);Check(Server.Engines.Points.PointsSystem.CleanUpBritannia.GetPoints(owner)==balance+value,"empty trash cannot award twice");trash.Delete();var publicTrash=new HavenPublicTrashChest();publicTrash.MoveToWorld(owner.Location,owner.Map);var publicScrap=new Katana();publicScrap.WeaponAttributes.HitLeechMana=50;publicScrap.WeaponAttributes.HitLeechHits=50;var nestedTrash=new Bag();nestedTrash.DropItem(publicScrap);double publicValue=Server.Engines.Points.CleanUpBritanniaData.GetPoints(publicScrap);double publicBefore=Server.Engines.Points.PointsSystem.CleanUpBritannia.GetPoints(owner);Check(publicTrash.OnDragDropInto(owner,nestedTrash,new Point3D(40,40,0)),"public trash accepts nested scrap via open container");owner.Backpack.DropItem(publicScrap);Check(publicTrash.m_Cleanup.Count==0,"retrieving nested scrap cancels pending credit");publicTrash.Empty(501479);Check(publicTrash.OnDragDrop(owner,publicScrap),"public trash accepts direct drop");publicTrash.Empty(501479);Check(Server.Engines.Points.PointsSystem.CleanUpBritannia.GetPoints(owner)==publicBefore+publicValue,"public trash credits depositor once");publicTrash.Delete();
 var post=HavenFreePetHitchingPost.Ensure();Check(post!=null&&post.Map==Map.Trammel,"Haven pet shrinking post placed");Check(HavenFreePetHitchingPost.Ensure()==post,"post placement is idempotent");owner.MoveToWorld(post.Location,post.Map);var shrinkPet=new Horse();shrinkPet.MoveToWorld(owner.Location,owner.Map);shrinkPet.SetControlMaster(owner);shrinkPet.Skills.Wrestling.Base=72.3;Check(post.Shrink(owner,shrinkPet),"free hitching post stores owned pet");var shrinkTicket=owner.Backpack.FindItemsByType(typeof(HavenPetTicket),true).Cast<HavenPetTicket>().First(x=>x.Pet==shrinkPet);Check(shrinkTicket.Claim(owner)&&shrinkPet.ControlMaster==owner&&shrinkPet.Skills.Wrestling.Base==72.3,"hitching post restores exact trained pet");shrinkPet.Delete();owner.MoveToWorld(new Point3D(1015,527,-65),Map.Malas);
 var areaBow=new HavenFrostwakeBow();var areaVictim=new Ogre();var areaNeighbor=new Ogre();var areaFriendly=new Horse();var savedAreaLocation=owner.Location;var savedAreaMap=owner.Map;owner.MoveToWorld(new Point3D(3350,2600,Map.Trammel.GetAverageZ(3350,2600)),Map.Trammel);areaVictim.MoveToWorld(new Point3D(3358,2600,Map.Trammel.GetAverageZ(3358,2600)),Map.Trammel);areaNeighbor.MoveToWorld(new Point3D(3358,2601,Map.Trammel.GetAverageZ(3358,2601)),Map.Trammel);areaFriendly.MoveToWorld(areaNeighbor.Location,Map.Trammel);areaFriendly.SetControlMaster(owner);int neighborHits=areaNeighbor.Hits;int friendlyHits=areaFriendly.Hits;areaBow.DoAreaAttack(owner,areaVictim,80,0xFC,2100,0,0,100,0,0);Check(areaNeighbor.Hits<neighborHits,"frost bow area damage reaches enemies around ranged target");Check(areaFriendly.Hits==friendlyHits,"area weapon native targeting excludes owned pet");areaVictim.Delete();areaNeighbor.Delete();areaFriendly.Delete();areaBow.Delete();owner.Combatant=null;owner.Aggressors.Clear();owner.Aggressed.Clear();owner.MoveToWorld(savedAreaLocation,savedAreaMap);
 var trainPet=new HavenEmberwing();trainPet.MoveToWorld(owner.Location,owner.Map);trainPet.SetControlMaster(owner);trainPet.ControlSlotsMax=5;owner.Skills.AnimalTaming.Cap=125;owner.Skills.AnimalTaming.Base=125;
 var trainProfile=PetTrainingHelper.GetTrainingProfile(trainPet,true);trainProfile.BeginTraining();trainProfile.TrainingProgress=trainProfile.TrainingProgressMax;
 for(int category=0;category<5;category++){var screen=new HavenPetTrainingGump(trainPet,category);Check(screen.Entries.OfType<Server.Gumps.GumpButton>().All(b=>b.NormalID==210),"training category has flat controls "+category);}
 var strengthPoint=PetTrainingHelper.GetTrainingPoint(PetStat.Str);int startStrength=trainPet.RawStr;int pointsBefore=trainProfile.TrainingPoints;int slotsBefore=trainPet.ControlSlots;
 Check(HavenPetTrainingMenu.Purchase(owner,trainPet,strengthPoint,startStrength,startStrength+1),"native training stat purchase succeeds");Check(trainPet.RawStr==startStrength+1&&trainPet.ControlSlots==slotsBefore+1&&trainProfile.TrainingPoints<pointsBefore,"training deducts native points and adds first follower slot");Check(!HavenPetTrainingMenu.Purchase(owner,trainPet,strengthPoint,startStrength,startStrength+1),"stale training purchase cannot repeat");
 for(int choice=0;choice<3;choice++){var prize=HavenMiniPrize.WhirlwindReward(0.049,choice);Check(prize!=null&&prize.Layer==Layer.OneHanded&&prize.PrimaryAbility==WeaponAbility.WhirlwindAttack,"mini champ reward supplies one handed whirlwind choice "+choice);HavenAdvancedGear.Find(prize).Delete();prize.Delete();}Check(HavenMiniPrize.WhirlwindReward(0.05,0)==null,"mini champ whirlwind five percent boundary");
 var oneHand=new HavenCycloneScimitar();Check(oneHand.Layer==Layer.OneHanded&&oneHand.PrimaryAbility==WeaponAbility.WhirlwindAttack,"scimitar supports native one-handed Whirlwind");HavenAdvancedGear.Find(oneHand).Delete();oneHand.Delete();
 var manaPoint=PetTrainingHelper.GetTrainingPoint(PetStat.Mana);int manaStart=HavenPetTrainingMenu.Current(trainPet,manaPoint),manaPoints=trainProfile.TrainingPoints;int savedBudget=trainProfile.TrainingPoints;trainProfile.TrainingPoints=1;Check(HavenPetTrainingMenu.AffordableMaximum(trainPet,manaPoint)==manaStart+2,"Max affordable spends remaining one point on two mana");trainProfile.TrainingPoints=savedBudget;Check(HavenPetTrainingMenu.AdjustmentStep(manaPoint)==2,"mana adjustment uses two mana per training point");Check(!HavenPetTrainingMenu.Purchase(owner,trainPet,manaPoint,manaStart,manaStart+1)&&trainProfile.TrainingPoints==manaPoints,"fractional mana purchase cannot obtain a rounded free point");Check(HavenPetTrainingMenu.Purchase(owner,trainPet,manaPoint,manaStart,manaStart+2)&&HavenPetTrainingMenu.Current(trainPet,manaPoint)==manaStart+2&&trainProfile.TrainingPoints==manaPoints-1,"two mana costs exactly one training point");
 trainPet.Skills.Wrestling.Base=50;trainPet.Skills.Wrestling.Cap=100;var capPoint=PetTrainingHelper.GetTrainingPoint(SkillName.Wrestling);int beforeScroll=trainProfile.TrainingPoints;Check(!HavenPetTrainingMenu.Purchase(owner,trainPet,capPoint,0,50)&&trainProfile.TrainingPoints==beforeScroll,"skill cap purchase requires native matching scroll without spending points");var matchingScroll=new PowerScroll(SkillName.Wrestling,105);owner.Backpack.DropItem(matchingScroll);Check(HavenPetTrainingMenu.Purchase(owner,trainPet,capPoint,0,50)&&matchingScroll.Deleted&&trainPet.Skills.Wrestling.Cap==105,"native scroll consumed only on successful skill cap training");
 trainProfile.TrainingProgress=0;int savedStrength=trainPet.RawStr;Check(!HavenPetTrainingMenu.Purchase(owner,trainPet,strengthPoint,savedStrength,savedStrength+1),"incomplete combat training cannot buy upgrades");trainProfile.TrainingProgress=trainProfile.TrainingProgressMax;trainPet.MoveToWorld(new Point3D(owner.X+40,owner.Y,owner.Z),owner.Map);Check(!HavenPetTrainingMenu.Purchase(owner,trainPet,strengthPoint,savedStrength,savedStrength+1),"remote training purchase rejected");trainPet.Delete();
 for(int areaIndex=0;areaIndex<3;areaIndex++){var weapon=HavenAreaWeapons.Create(areaIndex);var record=HavenAdvancedGear.Find(weapon);Check(record!=null&&record.Level==1&&weapon.MaxHitPoints>=255,"area weapon starts leveling with enhanced durability");record.Gain(1900);int proc=areaIndex==0?weapon.WeaponAttributes.HitEnergyArea:areaIndex==1?weapon.WeaponAttributes.HitFireArea:weapon.WeaponAttributes.HitColdArea;Check(proc==77&&record.Level==20&&record.Experience==1900,"area weapon proc grows to77 at level20");int damage=weapon.Attributes.WeaponDamage;record.Gain(10);record.Apply();Check(weapon.Attributes.WeaponDamage==damage&&record.Experience==1900,"max area weapon cannot stack bonuses");using(var stream=new MemoryStream()){var writer=new BinaryFileWriter(stream,true);record.Serialize(writer);writer.Flush();stream.Position=0;record.Deserialize(new BinaryFileReader(new BinaryReader(stream)));}Check(record.Equipment==weapon&&record.Level==20&&record.Experience==1900&&record.Kind==6,"area weapon saved progression roundtrip");record.Delete();weapon.Delete();}
 var c=HavenCompanion.Claim(owner);
 owner.RawInt=100;owner.Mana=owner.ManaMax;owner.Skills.Magery.Cap=120;owner.Skills.Magery.Base=120;
 c.MoveToWorld(new Point3D(3550,2580,14),Map.Trammel);var recallScroll=new RecallScroll();owner.Backpack.DropItem(recallScroll);var actualRecall=new Server.Spells.Fourth.RecallSpell(owner,recallScroll);owner.Spell=actualRecall;actualRecall.State=Server.Spells.SpellState.Sequencing;var actualDestination=new Point3D(3500,2580,14);actualRecall.Effect(actualDestination,Map.Trammel,false);Check(owner.Map==Map.Trammel&&owner.Location==actualDestination&&c.Location==owner.Location&&c.Map==owner.Map,"real Recall spell sequence carries distant companion");Check(recallScroll.Deleted,"real Recall sequence consumed its scroll");owner.MoveToWorld(new Point3D(1015,527,-65),Map.Malas);c.MoveToWorld(owner.Location,owner.Map);
 var travelCargo=new Gold(123);c.Backpack.DropItem(travelCargo);c.IsBonded=false;c.MoveToWorld(new Point3D(3500,2580,14),Map.Trammel);var travelLanding=owner.Location;BaseCreature.TeleportPets(owner,travelLanding,owner.Map,true);Check(c.Map==owner.Map&&c.Location==travelLanding&&c.ControlTarget==owner&&c.ControlOrder==OrderType.Follow,"bonded-only spell path brings distant unbonded companion across facets");Check(travelCargo.Parent==c.Backpack&&travelCargo.Amount==123,"companion spell travel retains inventory");
 var followStart=c.Location;owner.MoveToWorld(new Point3D(c.X+4,c.Y,c.Z),c.Map);c.AIObject.NextMove=Core.TickCount;c.AIObject.DoOrderFollow();Check(c.Location!=followStart,"companion actually walks after spell teleport");owner.MoveToWorld(travelLanding,owner.Map);c.MoveToWorld(owner.Location,owner.Map);
 var travelGate=new Moongate(new Point3D(3500,2580,14),Map.Trammel);travelGate.OnGateUsed(owner);Check(c.Map==Map.Trammel&&c.Location==owner.Location,"gate travel carries companion through shared native path");travelGate.Delete();
 var unbondedPet=new Horse();unbondedPet.MoveToWorld(owner.Location,owner.Map);unbondedPet.SetControlMaster(owner);unbondedPet.ControlOrder=OrderType.Follow;var petBefore=unbondedPet.Location;BaseCreature.TeleportPets(owner,new Point3D(owner.X+20,owner.Y,owner.Z),owner.Map,true);Check(unbondedPet.Location==petBefore,"ordinary unbonded pets retain native Recall rule");unbondedPet.Delete();c.MoveToWorld(owner.Location,owner.Map);
 Check(c.StartMission(owner,5,CompanionMission.Supply),"dispatch mission before owner spell travel");var awayPoint=c.Location;var awayMap=c.Map;BaseCreature.TeleportPets(owner,new Point3D(owner.X+20,owner.Y,owner.Z),owner.Map,true);Check(c.OnMission&&c.Location==awayPoint&&c.Map==awayMap,"owner spell travel leaves mission and timer intact");Check(c.Recall(owner),"manual recall still returns away companion");travelCargo.Delete();owner.MoveToWorld(travelLanding,Map.Malas);c.MoveToWorld(owner.Location,owner.Map);
 Check(HavenCompanionStatsGump.Rows(c,2,0,new double[c.Skills.Length]).Length==c.Skills.Length,"all-skills view includes every skill across pages");var skillScreen=new HavenCompanionStatsGump(c);Check((int)typeof(HavenCompanionStatsGump).GetField("_filter",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).GetValue(skillScreen)==2,"skill screen defaults to all skills");
 c.Skills.AnimalTaming.Base=73; c.Skills.AnimalTaming.Base=50;Check(c.Skills.AnimalTaming.Base==73,"earned taming cannot reset downward");
var bag=new Bag();var gold=new Gold(200);bag.DropItem(gold);c.Backpack.DropItem(bag);

 Check(HavenTamingSupplies.SearchRolls(5)==1&&HavenTamingSupplies.SearchRolls(15)==3&&HavenTamingSupplies.SearchRolls(30)==6&&HavenTamingSupplies.SearchRolls(60)==15,"duration search rolls match old server");
 foreach(var entry in new[]{Tuple.Create(0.0,typeof(HavenBondingPotion)),Tuple.Create(0.08,typeof(HavenPetLeash)),Tuple.Create(0.16,typeof(PowerScroll)),Tuple.Create(0.25,typeof(HavenHouseHitchingPost))}){var reward=HavenTamingSupplies.Bonus(entry.Item1);Check(reward.GetType()==entry.Item2,"taming bonus "+entry.Item2.Name);reward.Delete();}Check(HavenTamingSupplies.Bonus(0.27)==null,"no bonus above configured rates");
 var leash=new HavenPetLeash();owner.Backpack.DropItem(leash);var leashPet=new Horse();leashPet.MoveToWorld(owner.Location,owner.Map);leashPet.SetControlMaster(owner);Check(HavenFreePetHitchingPost.ShrinkFrom(leash,owner,leashPet),"portable reusable leash shrinks pet");var leashTicket=owner.Backpack.FindItemsByType(typeof(HavenPetTicket),true).Cast<HavenPetTicket>().First(t=>t.Pet==leashPet);Check(leashTicket.Claim(owner)&&!leash.Deleted,"leash remains reusable and pet returns");var potion=new HavenBondingPotion();owner.Backpack.DropItem(potion);Check(potion.ApplyTo(owner,leashPet)&&leashPet.IsBonded&&potion.Deleted,"bonding potion bonds owned pet and consumes once");leashPet.Delete();leash.Delete();
 Check(c.StartMission(owner,60,CompanionMission.TamePackHorse),"sixty minute taming dispatch");var scheduled=(HavenPetTicket)typeof(HavenCompanion).GetField("_scheduledPet",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).GetValue(c);var supply=(Bag)typeof(HavenPetTicket).GetField("_supplies",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).GetValue(scheduled);Check(supply!=null&&supply.Map==Map.Internal,"taming supplies fixed at dispatch");supply.DropItem(new HavenHouseHitchingPost());typeof(HavenCompanion).GetMethod("CompletePetMission",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).Invoke(c,null);Check(supply.Parent==c.Backpack&&supply.FindItemByType(typeof(HavenHouseHitchingPost))!=null,"completed taming supplies delivered to companion pack");Check(c.Recall(owner),"return from completed test trip");c.DeliverPetTickets();
 foreach(var screen in new Server.Gumps.Gump[]{new CompanionGump(c),new CompanionActivityGump(c,1),new HavenCompanionStatsGump(c),new HavenCompanionRolesGump(c),new HavenCompanionPetsGump(c),new HavenOfflineMissionGump(HavenOfflineMissionPlan.Ensure(c)),new HavenPetLoreGump(c,0),new HavenPetLoreGump(c,1),new HavenPetLoreGump(c,2)}){Check(screen.Entries.OfType<Server.Gumps.GumpButton>().All(b=>b.NormalID==210),"flat labeled controls "+screen.GetType().Name);}

 Check(c.StartMission(owner,5,CompanionMission.TamePackHorse),"dispatch cancellation test");var cancelled=(HavenPetTicket)typeof(HavenCompanion).GetField("_scheduledPet",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).GetValue(c);var cancelledBag=(Bag)typeof(HavenPetTicket).GetField("_supplies",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).GetValue(cancelled);Check(c.Recall(owner)&&cancelled.Deleted&&cancelledBag.Deleted,"early recall deletes unearned pet and supplies");

 var overview=new HavenAnimalLoreGump(owner,c);Check(overview.Entries.OfType<Server.Gumps.GumpLabel>().Any(x=>x.Text=="Combat ratings")&&overview.Entries.OfType<Server.Gumps.GumpLabel>().Any(x=>x.Text=="Lore and magic"),"original overview combat and lore columns restored");
 var ember=new HavenEmberwing();for(int loreTab=0;loreTab<5;loreTab++){var lore=new HavenPetLoreGump(ember,loreTab);Check(lore.Entries.OfType<Server.Gumps.GumpButton>().Select(x=>x.ButtonID).Distinct().Contains(14),"original five lore tabs available on page "+loreTab);}Check(HavenPetLore.Story(ember).StartsWith("Emberwings nest"),"original Emberwing story available");ember.Delete();
 var listener=new System.Net.Sockets.TcpListener(System.Net.IPAddress.Loopback,0);listener.Start();var client=new System.Net.Sockets.TcpClient();client.Connect((System.Net.IPEndPoint)listener.LocalEndpoint);var net=new Server.Network.NetState(new Server.Network.SocketState(listener.AcceptSocket(),new byte[4]));owner.NetState=net;
 try{Check(c.StartMission(owner,5,CompanionMission.Supply),"persistent timer test dispatch");var maintain=typeof(CompanionMissionTimerGump).GetMethod("Maintain",System.Reflection.BindingFlags.Static|System.Reflection.BindingFlags.NonPublic);maintain.Invoke(null,null);Check(owner.HasGump(typeof(CompanionMissionTimerGump)),"timer opens while mission active");owner.CloseGump(typeof(CompanionMissionTimerGump));maintain.Invoke(null,null);Check(owner.HasGump(typeof(CompanionMissionTimerGump)),"persistent timer restores after menu closes it");var mini=new CompanionMissionTimerGump(c,owner);Check(!mini.Closable,"mission timer cannot be accidentally right-clicked away");Check(c.Recall(owner),"persistent timer early recall");maintain.Invoke(null,null);Check(!owner.HasGump(typeof(CompanionMissionTimerGump)),"timer closes after recall");}finally{owner.NetState=null;net.Dispose();client.Close();listener.Stop();}
 Check(c.Backpack.MaxItems==1000&&c.Backpack.MaxWeight==0,"1000 item unlimited-weight companion pack");
 foreach(CompanionRole role in new[]{CompanionRole.Warrior,CompanionRole.Caster,CompanionRole.Archer,CompanionRole.Bard,CompanionRole.Healer}){
 Check(c.SetRole(owner,role),"role "+role);Check(!c.AIObject.DoOrderRelease()&&c.ControlMaster==owner,"native release blocked "+role);c.DropBackpack();Check(bag.Parent==c.Backpack&&gold.Parent==bag,"inventory retained "+role);
 }
 c.MoveToWorld(new Point3D(2000,1500,0),Map.Trammel);Check(c.Recall(owner)&&c.Map==owner.Map&&c.Location==owner.Location,"recall from another facet at any distance");
 c.MoveToWorld(new Point3D(1500,1500,0),owner.Map);Check(c.Recall(owner)&&c.Location==owner.Location,"recall across the same facet");
 Check(c.StartMission(owner,30,CompanionMission.Mining),"mission dispatch");Check(bag.Parent==c.Backpack&&gold.Parent==bag,"nested items retained while away");Check(c.Recall(owner),"early recall");Check(bag.Parent==c.Backpack&&gold.Parent==bag&&gold.Amount==200,"same items return unchanged");
 var horse=new Horse();horse.MoveToWorld(owner.Location,owner.Map);horse.SetControlMaster(owner);Check(horse.AIObject.DoOrderRelease()&&!horse.Controlled,"ordinary pet release unchanged");horse.Delete();
 var source=HavenMiniChamp.Find();Check(source!=null,"existing verified mini camp");var camp=new HavenMiniChamp();camp.MoveToWorld(source.Location,source.Map);owner.MoveToWorld(camp.Location,camp.Map);c.MoveToWorld(owner.Location,owner.Map);
 HavenExpeditionMarker.Ensure(camp);bool foundMarkerEdge=false;foreach(var mark in World.Items.Values.OfType<HavenExpeditionMarker>().Where(x=>x.Map==camp.Map&&x.InRange(camp,12)).ToArray()){for(int dx=-3;dx<=3&&!foundMarkerEdge;dx++)for(int dy=-3;dy<=3&&!foundMarkerEdge;dy++){var edge=new Point3D(mark.X+dx,mark.Y+dy,mark.Map.GetAverageZ(mark.X+dx,mark.Y+dy));if(Math.Max(Math.Abs(edge.X-camp.X),Math.Abs(edge.Y-camp.Y))<=8||!mark.Map.CanFit(edge,16,false,false))continue;owner.MoveToWorld(edge,mark.Map);if(HavenExpeditionMarker.Nearby(camp,owner)){foundMarkerEdge=true;for(int variant=0;variant<4;variant++)Check(camp.StartError(owner,variant)==null,"variant "+variant+" accepts visible marker beyond controller radius");}}if(foundMarkerEdge)break;}Check(foundMarkerEdge,"tested marker edge outside eight tiles");
 owner.MoveToWorld(new Point3D(camp.X+40,camp.Y+40,camp.Z),camp.Map);Check(camp.StartError(owner,3).Contains("Move beside"),"start explains distance precisely");owner.MoveToWorld(camp.Location,camp.Map);c.MoveToWorld(owner.Location,owner.Map);
 var staleTarget=new Horse();staleTarget.MoveToWorld(new Point3D(owner.X+50,owner.Y+50,owner.Z),owner.Map);owner.Combatant=staleTarget;foreach(var record in owner.Aggressors.Concat(owner.Aggressed))typeof(AggressorInfo).GetField("m_LastCombatTime",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).SetValue(record,DateTime.UtcNow.AddMinutes(-10));Check(camp.StartError(owner,3)==null,"stale distant target and expired combat do not block start");owner.Combatant=null;owner.Aggressors.Clear();owner.Aggressed.Clear();staleTarget.Delete();
 for(int variant=0;variant<4;variant++){var freshCamp=new HavenMiniChamp();freshCamp.MoveToWorld(camp.Location,camp.Map);Check(freshCamp.Begin(owner,variant)&&freshCamp.Remaining==(variant==3?15:5),"actual start spawns enemies for variant "+variant);freshCamp.Delete();}
 int marksBeforeChallenge=HavenMarks.Balance(owner);
 Check(camp.Begin(owner,3),"start combined challenge");var foesField=typeof(HavenMiniChamp).GetField("_foes",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic);var spawn=typeof(HavenMiniChamp).GetMethod("SpawnWave",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic);
 for(int stage=0;stage<4;stage++){var foes=(System.Collections.Generic.List<Mobile>)foesField.GetValue(camp);Check(foes.Count==(stage==3?3:15),"challenge population stage "+stage);Check(System.Linq.Enumerable.Distinct(System.Linq.Enumerable.Select(foes,x=>x.Name)).Count()==3,"all three variants present");camp.Credit((HavenMiniEnemy)foes[0],owner,1);foreach(var foe in foes.ToArray()){camp.Defeated((HavenMiniEnemy)foe);foe.Delete();}if(stage<3)spawn.Invoke(camp,null);}
 Check(!camp.Active,"challenge completes only after all bosses");Check(HavenMarks.Balance(owner)==marksBeforeChallenge+80,"challenge awards eighty Marks");Check(owner.Backpack.FindItemsByType(typeof(AstralShard),true).Sum(x=>x.Amount)==1,"challenge awards one guaranteed bonus Astral Shard");Check(owner.Backpack.FindItemsByType(typeof(BankCheck),true).Cast<BankCheck>().Sum(x=>x.Worth)==40000,"challenge awards four gold reward bundles");var havenPrize=new HavenMiniPrize(owner,1);Check(havenPrize.FindItemByType(typeof(Cannonball))==null&&havenPrize.FindItemByType(typeof(PowderCharge))==null&&havenPrize.FindItemByType(typeof(FuseCord))==null,"Haven mini champ excludes island ship supplies");havenPrize.Delete();var pirate=new HavenMiniPrize(owner,1,true);Check(pirate.FindItemByType(typeof(Cannonball))!=null&&pirate.FindItemByType(typeof(PowderCharge))!=null&&pirate.FindItemByType(typeof(FuseCord))!=null,"native ship ammunition in corsair prize");pirate.Delete();camp.Delete();
 c.Criminal=true;owner.Criminal=false;owner.DoBeneficial(c);Check(!owner.Criminal,"owner care of criminal companion does not create a flag");
 owner.Criminal=true;var expiry=typeof(Mobile).GetField("m_ExpireCriminal",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic);var timer=(Timer)expiry.GetValue(owner);var crimeCount=owner.Crimes;owner.DoBeneficial(c);Check(owner.Criminal&&owner.Crimes==crimeCount,"owner care preserves existing expiry");
 var stranger=new PlayerMobile{Player=true};stranger.Criminal=true;Check(owner.IsBeneficialCriminal(stranger),"unrelated criminal aid remains criminal");
 c.Criminal=false;owner.Criminal=false;c.Internalize();c.CriminalAction(false);Check(owner.Criminal,"actual companion crime still flags owner");
 owner.Criminal=false;c.Criminal=false;c.MoveToWorld(owner.Location,owner.Map);stranger.Delete();
RestoredItemsSmoke.Run(owner,c,Check);
c.Delete();owner.Delete();File.AppendAllText("inventory-checks.log","COMPLETE\n");
 }catch(Exception e){File.AppendAllText("inventory-checks.log","FAIL "+e+"\n");}Core.Kill(false);}
}
