using System;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Net;
using System.Net.Sockets;
using Server;
using Server.Items;
using Server.Mobiles;
using Server.Network;
using Server.Accounting;
using Server.Spells.SkillMasteries;
using Server.HavenPrototype;
public static class CompanionRolesV2Smoke {
 static PlayerMobile owner;static HavenCompanion c;static Horse horse;static NetState net;static TcpClient client;static TcpListener listener;
 static void Check(bool ok,string s){if(!ok)throw new Exception(s);File.AppendAllText("roles-v2-checks.log","PASS "+s+"\n");}
 static void Reset(string field){typeof(HavenCompanion).GetField(field,BindingFlags.NonPublic|BindingFlags.Instance).SetValue(c,DateTime.MinValue);}
 public static void Initialize(){if(File.Exists("ROLE-V2-TEST-ONLY"))EventSink.ServerStarted+=()=>Timer.DelayCall(TimeSpan.FromSeconds(8),Run);}
 static void Run(){try{
 var saved=World.Mobiles.Values.OfType<HavenCompanion>().FirstOrDefault(x=>x.BoundOwner?.Name=="Roles zero-slot fixture");if(saved!=null){var p=(PlayerMobile)saved.BoundOwner;p.MoveToWorld(new Point3D(1015,527,-65),Map.Malas);p.ClaimAutoStabledPets();Check(saved.ControlSlots==0,"old one-slot saved companion migrates to zero");Check(p.Followers==p.AllFollowers.OfType<BaseCreature>().Where(x=>x.Controlled&&x.ControlMaster==p).Sum(x=>x.ControlSlots),"owner follower count matches actual pets after migration");Check(saved.Role==CompanionRole.Healer&&saved.AIObject is HavenCompanionHealerAI,"healer role and AI survive reload");Check(saved._roleTrainingMinutes>=123,"support progression survives reload");int slots=p.Followers;saved.EnsureFreeFollowerSlots();saved.EnsureFreeFollowerSlots();Check(p.Followers==slots,"slot migration is idempotent");File.AppendAllText("roles-v2-checks.log","RELOAD COMPLETE\n");Core.Kill(false);return;}
 owner=new PlayerMobile{Player=true,Body=0x190,RawStr=250};owner.AddItem(new Backpack());new Account("roles-"+Guid.NewGuid().ToString("N"),Guid.NewGuid().ToString("N"))[0]=owner;owner.MoveToWorld(new Point3D(1015,527,-65),Map.Malas);horse=new Horse{ControlSlots=5,CantWalk=true};Check(horse.SetControlMaster(owner),"ordinary five-slot pet fits");horse.MoveToWorld(owner.Location,owner.Map);Check(owner.Followers==5,"ordinary pet still consumes its slots");c=HavenCompanion.Claim(owner);Check(c!=null&&c.ControlSlots==0&&owner.Followers==5,"companion can be recruited with all pet slots occupied");Check(HavenCompanion.Claim(owner)==c&&owner.Followers==5,"repeated claim does not alter follower count");c.Skills.Healing.Base=100;c.Skills.Anatomy.Base=100;
 owner.Hits=50;Check(c.SupportPatient(owner),"all-role basic heal still works");int basic=owner.Hits-50;Reset("_nextHeal");owner.Hits=50;Check(c.SetRole(owner,CompanionRole.Healer)&&c.AIObject is HavenCompanionHealerAI,"dedicated healer role available");Check(c.SupportPatient(owner)&&owner.Hits-50>basic,"healer direct heal is stronger than basic role");Reset("_nextHeal");owner.Hits=owner.HitsMax-5;horse.Hits=1;Check(c.HealMostUrgent()&&horse.Hits>1&&owner.Hits==owner.HitsMax-5,"healer prioritizes critically wounded pet over minor owner damage");owner.Hits=50;horse.Hits=1;c.Mana=c.ManaMax;var stranger=new PlayerMobile{Player=true,Body=0x190,RawStr=250};stranger.MoveToWorld(owner.Location,owner.Map);stranger.Hits=1;Check(c.HealerRecoveryPulse()&&owner.Hits>50&&horse.Hits>1&&stranger.Hits==1,"emergency recovery heals allies and excludes unrelated players");Check(!c.HealerRecoveryPulse(),"group recovery respects twenty-second cooldown");Check(!c.Attack(owner,stranger),"healer does not abandon support to attack");stranger.Delete();owner.Hits=owner.HitsMax;horse.Hits=horse.HitsMax;
 Check(c.SetRole(owner,CompanionRole.Bard),"Bard role available");foreach(var skill in new[]{SkillName.Musicianship,SkillName.Peacemaking,SkillName.Discordance,SkillName.Provocation})c.Skills[skill].Base=80;Check(c.BardSong(owner)&&owner.GetStatMod("HavenCompanionSongStr")!=null,"original low-skill encouragement song applies");int strength=owner.GetStatMod("HavenCompanionSongStr").Offset;c.BardSong(owner);Check(owner.GetStatMod("HavenCompanionSongStr").Offset==strength,"repeated songs refresh without stacking");c.ClearRoleSupport();Check(owner.GetStatMod("HavenCompanionSongStr")==null,"song cleanup removes its stat buffs");foreach(var skill in new[]{SkillName.Musicianship,SkillName.Peacemaking,SkillName.Discordance,SkillName.Provocation})c.Skills[skill].Base=125;owner.Hits=20;Check(c.ChooseBardMastery(null)==SkillName.Peacemaking,"wounded owner selects defensive mastery");owner.Hits=owner.HitsMax;Check(c.ChooseBardMastery(null)==SkillName.Provocation,"healthy group selects offensive support mastery");Check(c.JoinOwnerParty(owner),"native party includes companion for mastery effects");
 listener=new TcpListener(IPAddress.Loopback,0);listener.Start();client=new TcpClient();client.Connect((IPEndPoint)listener.LocalEndpoint);net=new NetState(new SocketState(listener.AcceptSocket(),new byte[4]));owner.NetState=net;c.Mana=c.ManaMax;Reset("_nextMastery");Check(c.ThinkBardMasteries(),"native mastery casting begins");Timer.DelayCall(TimeSpan.FromSeconds(15),AfterMastery);
 }catch(Exception e){Fail(e);}}
 static void AfterMastery(){try{var songs=SkillMasterySpell.GetSpells(c);Check(songs!=null&&songs.Any(x=>x is InspireSpell&&x.Timer!=null)&&songs.Any(x=>x is InvigorateSpell&&x.Timer!=null),"native Inspire and Invigorate are active");Check(songs.Where(x=>x.PartyEffects&&x.Timer!=null).Any(x=>x.PartyList.Contains(owner)),"native mastery effects reach owner through party");c.ClearRoleSupport();Check(songs.All(x=>x.Timer==null),"changing activity expires all native Bard songs");Check(c.SetRole(owner,CompanionRole.Healer),"healer switch after mastery cleans casts");owner.NetState=null;net.Dispose();client.Close();listener.Stop();c._roleTrainingMinutes=123;owner.Name="Roles zero-slot fixture";horse.RemoveFollowers();horse.ControlSlots=4;horse.AddFollowers();c.RemoveFollowers();c.ControlSlots=1;c.AddFollowers();World.Save();File.AppendAllText("roles-v2-checks.log","FRESH COMPLETE\n");Core.Kill(false);}catch(Exception e){Fail(e);}}
 static void Fail(Exception e){File.AppendAllText("roles-v2-checks.log","FAIL "+e+"\n");Core.Kill(false);}
}
