using System;
using System.IO;
using System.Linq;
using System.Reflection;
using Server;
using Server.Items;
using Server.Mobiles;
using Server.Accounting;
using Server.HavenPrototype;
public static class ContentSmoke {
 static void Check(bool ok,string name){if(!ok)throw new Exception(name);File.AppendAllText("content-checks.log","PASS "+name+"\n");}
 public static void Initialize(){if(!File.Exists("CASTER-TEST-ONLY")&&File.Exists("CONTENT-TEST-ONLY"))EventSink.ServerStarted+=()=>Timer.DelayCall(TimeSpan.FromSeconds(4),Run);}
 static void Ready(HavenCompanion c){typeof(HavenCompanion).GetField("_nextHeal",BindingFlags.Instance|BindingFlags.NonPublic).SetValue(c,DateTime.MinValue);}
 static void Run(){try{
 var p=World.Mobiles.Values.OfType<PlayerMobile>().FirstOrDefault(x=>x.Name=="Content fixture v3");
 if(p!=null){var saved=p.Backpack.FindItemByType(typeof(HavenChampionCodex),true) as HavenChampionCodex;Check(saved!=null&&saved.Items.OfType<ScrollOfTranscendence>().Any(x=>x.Value==2.3),"Codex exact scroll values survive save reload");var savedShield=p.Items.OfType<BaseShield>().FirstOrDefault();Check(savedShield!=null&&HavenEquipmentEvolution.Find(savedShield).Level==20,"shield level and identity survive reload");HavenWardenPost.Ensure();Check(World.Items.Values.OfType<HavenWardenPost>().Count(x=>!x.Deleted)==1,"Warden marker remains unique after reload");Check(HavenWardenPost.Find().NextSpawn>DateTime.UtcNow,"Warden respawn cooldown survives reload");File.AppendAllText("content-checks.log","COMPLETE reload\n");Core.Kill(false);return;}
 p=new PlayerMobile{Player=true,Name="Content fixture v3",Body=0x190,RawStr=200};p.AddItem(new Backpack());new Account("content-fixture-v3",Guid.NewGuid().ToString("N"))[0]=p;p.MoveToWorld(new Point3D(1015,527,-65),Map.Malas);
 var book=new HavenChampionCodex();p.Backpack.DropItem(book);var nested=new Bag();p.Backpack.DropItem(nested);var trans=new ScrollOfTranscendence(SkillName.Mining,2.3);nested.DropItem(trans);var sword=new Longsword();nested.DropItem(sword);int slots=p.Backpack.TotalItems;Check(book.Collect(p,nested)==1&&trans.Parent==book&&sword.Parent==nested&&p.Backpack.TotalItems==slots-1,"Codex nested collection preserves exact items and excludes equipment");Check(book.TotalItems==0,"archived scrolls consume no extra pack slots");
 for(int i=0;i<8;i++)book.DropItem(new PowerScroll(SkillName.Magery,105));book.MaxItems=book.Items.Count;Check(book.Convert(p,SkillName.Magery,105,false)&&book.Items.OfType<PowerScroll>().Single().Value==110,"combine eight 105 into one 110 even at slot limit");book.MaxItems=1;Check(!book.Convert(p,SkillName.Magery,110,true)&&book.Items.OfType<PowerScroll>().Single().Value==110,"failed split preserves original scroll");book.MaxItems=0;Check(book.Convert(p,SkillName.Magery,110,true)&&book.Items.OfType<PowerScroll>().Count()==8,"split returns eight matching 105 scrolls");Check(!book.Convert(p,SkillName.Healing,105,false),"combine cannot consume another skill");var outsider=new PlayerMobile();Check(!book.Withdraw(outsider,trans)&&!book.Convert(outsider,SkillName.Magery,105,false),"Codex rejects nonowner access");outsider.Delete();Check(book.Withdraw(p,trans)&&trans.Value==2.3,"withdraw preserves exact Transcendence value");book.Collect(p,trans);book.MaxItems=book.Items.Count;var extra=new PowerScroll(SkillName.Healing,110);p.Backpack.DropItem(extra);Check(book.Collect(p,extra)==0&&extra.Parent==p.Backpack,"full Codex leaves incoming scroll intact");book.MaxItems=0;
 var c=HavenCompanion.Claim(p);c.MoveToWorld(p.Location,p.Map);c.Mana=c.ManaMax;p.Hits=10;int mana=c.Mana;Check(c.HealOwner(p)&&p.Hits>10&&c.Mana==mana-10,"companion owner healing costs mana");Check(!c.HealOwner(p),"healing cooldown prevents repeat spam");Ready(c);p.ApplyPoison(c,Poison.Regular);Check(c.HealOwner(p)&&!p.Poisoned,"companion cures owner poison");Ready(c);p.Kill();Check(c.HealOwner(p)&&!p.Alive,"companion offers resurrection without forcing acceptance");p.Resurrect();p.Criminal=false;p.Aggressors.Clear();p.Aggressed.Clear();Ready(c);c.Hits=10;Check(c.SupportPatient(c)&&c.Hits>10,"companion self healing works");
 var shield=new MetalKiteShield{Name="Boarding shield",Hue=0x489,HitPoints=17};HavenBoardingShieldUpgrade.Apply(shield);int resist=shield.PhysicalBonus;HavenBoardingShieldUpgrade.Apply(shield);Check(shield.Attributes.DefendChance==15&&shield.Attributes.BonusHits==15&&shield.PhysicalBonus==resist&&shield.HitPoints==17,"shield upgrade is idempotent and preserves wear");var shieldRecord=HavenEquipmentEvolution.Find(shield);shieldRecord.Gain(1900);Check(shieldRecord.Level==20&&shield.Attributes.BonusHits==30&&shield.HitPoints==17,"boarding shield reaches level 20 without repairing wear");p.AddItem(shield);
 HavenWardenPost.Ensure();var post=HavenWardenPost.Find();post.NextSpawn=DateTime.MinValue;post.Tick();Check(post!=null&&post.Warden!=null,"Warden marker and boss spawned at walkable site");var boss=post.Warden;p.MoveToWorld(boss.Location,boss.Map);c.MoveToWorld(boss.Location,boss.Map);int marks=HavenMarks.Balance(p);var weapon=c.FindItemOnLayer(Layer.OneHanded) as BaseWeapon;Check(weapon!=null&&weapon.WeaponAttributes.HitLeechMana>=60,"companion spawned weapon upgraded automatically");boss.Damage(boss.Hits+1,c);Check(HavenEquipmentEvolution.Find(weapon).Experience>0,"companion weapon earns XP from credited kill");Check(HavenMarks.Balance(p)>=marks+3&&HavenMarks.Balance(p)<=marks+6,"companion Warden kill credits owner Marks");Check(post.Warden==null&&post.NextSpawn>DateTime.UtcNow.AddSeconds(115),"boss death schedules respawn");Check(boss.Corpse!=null&&((Container)boss.Corpse).Items.Count>=3,"Warden corpse contains loot");post.Tick();Check(post.Warden==null,"cooldown prevents immediate duplicate spawn");
 HavenRecovery.Ensure();p.MoveToWorld(HavenRecovery.Steward().Location,Map.Trammel);p.Combatant=null;p.Aggressors.Clear();p.Aggressed.Clear();p.Criminal=false;var corpse=p.Corpse as Corpse;Check(corpse!=null&&HavenRecovery.RecallCorpse(p)&&corpse.Location==p.Location,"corpse summon still moves existing corpse");var menu=new HavenRecoveryGump();Check(menu.Entries.OfType<Server.Gumps.GumpButton>().Any(x=>x.ButtonID==3),"recovery menu exposes corpse summon button");
 World.Save(false,false);File.AppendAllText("content-checks.log","COMPLETE fresh\n");Core.Kill(false);
 }catch(Exception e){File.AppendAllText("content-checks.log","FAIL "+e+"\n");Core.Kill(false);}}
}
