using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Reflection;
using System.Net;
using System.Net.Sockets;
using Server;
using Server.Items;
using Server.Mobiles;
using Server.Accounting;
using Server.Network;
using Server.HavenPrototype;
public static class OfflineMissionSmoke {
 static void Check(bool ok,string s){if(!ok)throw new Exception(s);File.AppendAllText("offline-mission-checks.log","PASS "+s+"\n");}
 static void Complete(HavenCompanion c){var timer=typeof(HavenCompanion).GetField("_missionTimer",BindingFlags.Instance|BindingFlags.NonPublic).GetValue(c) as Timer;timer?.Stop();typeof(HavenCompanion).GetField("_missionDue",BindingFlags.Instance|BindingFlags.NonPublic).SetValue(c,DateTime.UtcNow.AddSeconds(-1));typeof(HavenCompanion).GetMethod("CompleteDueMission",BindingFlags.Instance|BindingFlags.NonPublic).Invoke(c,null);}
 public static void Initialize(){if(File.Exists("OFFLINE-MISSION-TEST-ONLY"))EventSink.ServerStarted+=()=>Timer.DelayCall(TimeSpan.FromSeconds(8),Run);}
 static void VerifyOptions(HavenCompanion c){var p=HavenOfflineMissionPlan.Find(c);var owner=c.BoundOwner;p.Enabled=true;p.Rotate=true;p.Cursor=(int)CompanionMission.AbyssIngredients;c.Skills.MagicResist.Base=0;p.Tick();Check(c.OnMission&&c.MissionKind==CompanionMission.Supply,"rotation skips unqualified route and continues through eligible routes");p.RecallOnLogin=false;var listener=new TcpListener(IPAddress.Loopback,0);listener.Start();var client=new TcpClient();client.Connect((IPEndPoint)listener.LocalEndpoint);var socket=listener.AcceptSocket();var net=new NetState(new SocketState(socket,new byte[4]));owner.NetState=net;var due=c.MissionDue;p.Tick();Check(c.OnMission&&c.MissionDue==due,"finish-on-login preserves the active trip and due time");p.Enabled=false;Check(c.Recall(owner),"manual recall remains available with offline repeat disabled");owner.NetState=null;net.Dispose();client.Close();listener.Stop();}
 static void Run(){try{
 var saved=World.Mobiles.Values.OfType<HavenCompanion>().FirstOrDefault(candidate=>candidate.BoundOwner?.Name=="Offline route fixture");if(saved!=null){var plan=HavenOfflineMissionPlan.Find(saved);Check(plan!=null&&plan.Enabled&&plan.Minutes==30&&plan.Focus==CompanionMission.DoomBones&&plan.ActiveTrip,"offline settings and active-trip identity survive reload");Check(saved.OnMission,"manual saved due time remains active after reload");int before=saved.CompletedMissions;Complete(saved);plan.Tick();Check(saved.CompletedMissions==before+1&&saved.OnMission&&saved.MissionKind==CompanionMission.DoomBones,"restart completion awards once and starts next chosen trip");plan.Tick();Check(saved.CompletedMissions==before+1,"repeated pulse cannot duplicate completion rewards");plan.Enabled=false;saved.BoundOwner.MoveToWorld(new Point3D(1015,527,-65),Map.Malas);Check(saved.Recall(saved.BoundOwner),"owner can recall offline trip after reload");VerifyOptions(saved);File.AppendAllText("offline-mission-checks.log","RELOAD COMPLETE\n");Core.Kill(false);return;}
 var owner=new PlayerMobile{Player=true,Body=0x190,RawStr=250};owner.AddItem(new Backpack());new Account("offline-"+Guid.NewGuid().ToString("N"),Guid.NewGuid().ToString("N"))[0]=owner;owner.MoveToWorld(new Point3D(1015,527,-65),Map.Malas);var c=HavenCompanion.Claim(owner);foreach(var n in new[]{SkillName.Magery,SkillName.Tactics,SkillName.Archery,SkillName.MagicResist}){c.Skills[n].Cap=125;c.Skills[n].Base=125;}
 Check(HavenResources.Types.Length==HavenResources.Names.Length,"resource names and serialized IDs stay aligned");foreach(var kind in HavenRegionalMissions.Kinds){var rewards=new Dictionary<int,int>();HavenRegionalMissions.Prepare(c,kind,60,rewards);Check(rewards.Count==(kind==CompanionMission.Reagents?8:kind==CompanionMission.MalasReagents?5:kind==CompanionMission.DoomBones?2:3),"original resource pool size "+kind);foreach(var pair in rewards){var item=HavenResources.Create(pair.Key,pair.Value);Check(item!=null&&item.Stackable,"native material is withdrawable "+HavenResources.Names[pair.Key]);item.Delete();}Check(c.StartMission(owner,60,kind),"60 minute dispatch "+kind);var scheduled=(Dictionary<int,int>)typeof(HavenCompanion).GetField("_scheduledResources",BindingFlags.Instance|BindingFlags.NonPublic).GetValue(c);var snapshot=scheduled.ToArray();var before=snapshot.ToDictionary(x=>x.Key,x=>c.ResourceLedger?.Balance(x.Key)??0);Complete(c);foreach(var pair in snapshot)Check(c.ResourceLedger.Balance(pair.Key)==before[pair.Key]+pair.Value,"snapshot reaches ledger exactly once");Check(c.Recall(owner),"return after regional completion");}
 c.Skills.MagicResist.Base=0;Check(c.MissionStartError(owner,5,CompanionMission.AbyssIngredients)!=null,"low resistance blocks regional mission despite high combat skills");c.Skills.MagicResist.Base=125;
 var p=HavenOfflineMissionPlan.Ensure(c);Check(p.Configure(owner,CompanionMission.Mining,30),"save chosen default and duration");p.Tick();Check(!c.OnMission,"offline repetition defaults off");Check(!c.StartOfflineMission(30,CompanionMission.Mining),"direct offline dispatch requires enabled plan");p.Enabled=true;Check(c.StartMission(owner,5,CompanionMission.Lumber),"manual mission starts before logout");p.Tick();Check(c.MissionKind==CompanionMission.Lumber,"offline plan preserves existing manual mission");Complete(c);p.Tick();Check(c.OnMission&&c.MissionKind==CompanionMission.Mining,"next trip uses saved offline default");int runs=c.CompletedMissions;p.Tick();Check(c.CompletedMissions==runs,"pulse never replaces running trip");p.Enabled=false;Complete(c);p.Tick();Check(!c.OnMission,"disabled plan does not dispatch next trip");Check(c.Recall(owner),"manual recall after offline completion");
 p.Enabled=true;p.Tick();p.RecallOnLogin=true;var listener=new TcpListener(IPAddress.Loopback,0);listener.Start();var client=new TcpClient();client.Connect((IPEndPoint)listener.LocalEndpoint);var socket=listener.AcceptSocket();var net=new NetState(new SocketState(socket,new byte[4]));owner.NetState=net;int completed=c.CompletedMissions;p.Tick();Check(!c.OnMission&&c.CompletedMissions==completed&&c.ControlOrder==OrderType.Follow,"login recall cancels early without extra rewards");Check(!c.StartOfflineMission(5,CompanionMission.Mining),"connected owner cannot start offline trip");owner.NetState=null;net.Dispose();client.Close();listener.Stop();
 p.RecallOnLogin=false;Check(p.Configure(owner,CompanionMission.DoomBones,30),"save regional offline default");p.Tick();Check(c.OnMission&&c.MissionKind==CompanionMission.DoomBones,"offline regional dispatch");owner.Name="Offline route fixture";World.Save();File.AppendAllText("offline-mission-checks.log","FRESH COMPLETE\n");Core.Kill(false);
 }catch(Exception e){File.AppendAllText("offline-mission-checks.log","FAIL "+e+"\n");Core.Kill(false);}}
}
