using System;
using System.Linq;
using System.IO;
using Server;
using Server.Items;
using Server.Mobiles;
using Server.HavenPrototype;
public static class RestoredItemsSmoke {
 public static void Run(Mobile p,HavenCompanion c,Action<bool,string> check){check(HavenAbyssTrial.RollRarity(0)==1&&HavenAbyssTrial.RollRarity(.30)==2&&HavenAbyssTrial.RollRarity(.75)==3,"hellhound rarity thresholds 30/45/25");check(HavenPetHabitats.SteedRarity(0)==0&&HavenPetHabitats.SteedRarity(.25)==1&&HavenPetHabitats.SteedRarity(.65)==2&&HavenPetHabitats.SteedRarity(.90)==3,"steed rarity thresholds 25/40/25/10");SmokeTeleportSmoke.Run(p,check);var bonusLoc=c.Location;var bonusMap=c.Map;c.MoveToWorld(new Point3D(3474,2602,10),Map.Trammel);check(HavenCompanionProgression.TrainingMultiplier(c)==2,"companion Haven training multiplier is two");c.MoveToWorld(new Point3D(1015,527,-65),Map.Malas);check(HavenCompanionProgression.TrainingMultiplier(c)==1,"companion training outside Haven remains normal");c.MoveToWorld(bonusLoc,bonusMap);
  check(HavenMissionLuck.Seconds(60,0)==3600&&HavenMissionLuck.Seconds(60,100)==3528,"mission luck saves two percent per hundred");
  check(HavenMissionLuck.Seconds(60,1667)==2400&&HavenMissionLuck.Seconds(60,int.MaxValue)==2400,"mission luck caps sixty minute trip at forty minutes");
  check(HavenMissionLuck.Seconds(5,2000)==200&&HavenMissionLuck.Seconds(15,2000)==600&&HavenMissionLuck.Seconds(30,2000)==1200,"mission luck applies same cap to every duration");
  p.Combatant=null;p.Aggressors.Clear();p.Aggressed.Clear();p.Criminal=false;c.Combatant=null;
  p.MoveToWorld(new Point3D(3500,2580,14),Map.Trammel);c.MoveToWorld(p.Location,p.Map);
  var combatFoe=new Horse();combatFoe.MoveToWorld(p.Location,p.Map);var combatRecord=AggressorInfo.Create(c,combatFoe,false);c.Aggressed.Add(combatRecord);c.Combatant=combatFoe;
  check(!HavenPetTrainingMenu.Peaceful(p,c),"recent companion combat blocks training");typeof(AggressorInfo).GetField("m_LastCombatTime",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).SetValue(combatRecord,DateTime.UtcNow.AddSeconds(-16));check(HavenPetTrainingMenu.Peaceful(p,c)&&!combatRecord.Expired,"training clears after fifteen seconds despite lingering target and native aggression");combatRecord.Refresh();check(!HavenPetTrainingMenu.Peaceful(p,c),"new pet attack resets short cooldown");c.Aggressed.Remove(combatRecord);c.Combatant=null;combatFoe.Delete();
  check(HavenMenuText.Encode("Haven's <pet>")=="Haven's &lt;pet&gt;","menu apostrophes render while markup stays escaped");
  var bandage=new HavenEndlessBandage();p.Backpack.DropItem(bandage);p.Hits=Math.Max(1,p.HitsMax-10);Bandage.BandageTargetRequest(bandage,p,p);check(BandageContext.GetContext(p)!=null&&!bandage.Deleted&&bandage.Amount==1,"native healing starts without consuming endless bandage");BandageContext.GetContext(p)?.StopHeal();bandage.Delete();p.Hits=p.HitsMax;
  var pouch=new HavenRunePouch();p.Backpack.DropItem(pouch);var blank=new RecallRune();p.Backpack.DropItem(blank);check(pouch.Store(p,blank)&&blank.Deleted&&pouch.Runes==1,"rune pouch stores ordinary blank");var named=new RecallRune{Name="keep me"};p.Backpack.DropItem(named);check(!pouch.Store(p,named)&&!named.Deleted,"rune pouch preserves personalized rune");named.Delete();
  check(!pouch.MarkRune(p,()=>false)&&pouch.Runes==1,"failed Mark preserves stored rune");
  p.Mana=p.ManaMax;var scroll=new MarkScroll();p.Backpack.DropItem(scroll);var spell=new Server.Spells.Sixth.MarkSpell(p,scroll);p.Spell=spell;spell.State=Server.Spells.SpellState.Sequencing;spell.OnCast();p.Target.Invoke(p,pouch);
  check(scroll.Deleted&&pouch.Runes==0&&p.Backpack.FindItemsByType(typeof(RecallRune),true).Cast<RecallRune>().Any(r=>r.Marked&&r.TargetMap==p.Map&&r.Target==p.Location),"real Mark spell targets pouch and produces marked rune");pouch.Delete();
  var map=new TreasureMap(1,Map.Trammel){Decoder=p,ChestLocation=new Point2D(3500,2580)};var shovel=new HavenGoldenShovel();p.Backpack.DropItem(map);p.Backpack.DropItem(shovel);check(shovel.Travel(p,map)&&!map.Completed&&!map.Deleted&&p.InRange(new Point3D(3500,2580,14),2)&&c.Map==p.Map&&c.Location==p.Location,"shovel lands beside decoded map with companion and preserves map");map.Completed=true;check(!shovel.Travel(p,map),"completed treasure map cannot trigger shovel travel");map.Delete();shovel.Delete();
  var steed=new HavenTideSteed();steed.SetControlMaster(p);steed.MoveToWorld(p.Location,p.Map);p.Skills.Fishing.Base=80;bool swim=p.CanSwim;double fishing=p.Skills.Fishing.Value;steed.Rider=p;File.AppendAllText("inventory-checks.log","Sea horse: rider="+(steed.Rider==p)+" swim="+p.CanSwim+" fishing="+fishing+" -> "+p.Skills.Fishing.Value+"\n");check(p.CanSwim&&Math.Abs(p.Skills.Fishing.Value-fishing-10)<0.001,"sea horse mounting grants swimming and ten fishing");var cargo=new Gold(25);steed.Backpack.DropItem(cargo);check(HavenTideCargoGump.Withdraw(steed,p,cargo)&&cargo.IsChildOf(p.Backpack),"mounted sea horse cargo can be withdrawn by owner");cargo.Delete();
  var visitor=new PlayerMobile{Player=true,Body=0x190};visitor.AddItem(new Backpack());visitor.MoveToWorld(p.Location,p.Map);var privateCargo=new Gold(20);steed.Backpack.DropItem(privateCargo);check(!HavenTideCargoGump.Withdraw(steed,visitor,privateCargo)&&privateCargo.Parent==steed.Backpack,"sea horse cargo rejects another player");visitor.Delete();
  steed.Rider=null;check(p.CanSwim==swim&&p.Skills.Fishing.Value==fishing,"sea horse dismount restores swimming and fishing");steed.Delete();
  var home=HavenStarterHome.Find(p)??HavenStarterHome.Claim(p);check(home!=null,"house exists for cartography access tests");var site=new Point3D(home.X+5,home.Y+5,home.Z+7);p.MoveToWorld(site,home.Map);
  var chest=new HavenMapStorageChest();chest.MoveToWorld(site,home.Map);var library=new HavenHouseMapLibrary();library.MoveToWorld(site,home.Map);
  check(chest.CanUse(p)&&HavenHouseMapLibrary.HouseAccess(p,library),"owner can access placed cartography storage and library");
  var nested=new Bag();p.Backpack.DropItem(nested);var chart=new TreasureMap(1,Map.Trammel);nested.DropItem(chart);var message=new SOS(Map.Trammel);nested.DropItem(message);var keep=new Gold(9);nested.DropItem(keep);
  check(chest.Collect(p,nested)==2&&chart.Parent==chest&&message.Parent==chest&&keep.Parent==nested,"map storage collects charts and SOS from nested bag without other items");
  check(chest.Withdraw(p,chart)&&chart.IsChildOf(p.Backpack),"map storage withdraws original chart");
  var stranger=new PlayerMobile{Player=true,Body=0x190};stranger.AddItem(new Backpack());stranger.MoveToWorld(site,home.Map);check(!chest.CanUse(stranger)&&!chest.Withdraw(stranger,message)&&!HavenHouseMapLibrary.HouseAccess(stranger,library),"cartography services reject stranger");stranger.Delete();
  check(HavenHouseMapLibraryGump.Catalog().Any(d=>d.Map==Map.Malas)&&HavenHouseMapLibraryGump.Catalog().Any(d=>d.Map==Map.TerMur),"library retains original expanded facet catalog");
  chest.Delete();library.Delete();chart.Delete();nested.Delete();p.MoveToWorld(new Point3D(3500,2580,14),Map.Trammel);c.MoveToWorld(p.Location,p.Map);
  for(int i=0;i<4;i++){var item=HavenWorldDiscoveries.UtilityItem(i);check(item!=null&&!item.Deleted,"original discovery utility factory "+i);item.Delete();}
  var enemy=new Horse();enemy.MoveToWorld(p.Location,p.Map);check(HavenWorldDiscoveries.Award(enemy,p,0.001),"original utility discovery interval awards restored item");check(!HavenWorldDiscoveries.Award(enemy,p,0.001),"utility discovery cannot duplicate same kill");enemy.Delete();
  c.Skills.AnimalTaming.Base=120;c.Skills.AnimalLore.Base=120;
  for(int i=0;i<10;i++){var t=new HavenPetTicket(p,0);p.Backpack.DropItem(t);check(HavenPetExchange.Exchange(p,t)&&t.Deleted,"unused mission ticket exchanges once");check(!HavenPetExchange.Exchange(p,t),"spent ticket cannot duplicate credits");}
  check(HavenPetExchange.Balance(p)==10,"pet credits accumulate separately from Marks");
  check(HavenPetExchange.Redeem(p,6,1)&&HavenPetExchange.Balance(p)==0,"credits redeem qualified rare pet reward");var reward=p.Backpack.FindItemsByType(typeof(HavenPetTicket),true).Cast<HavenPetTicket>().First(t=>t.Kind==6);check(reward.Rarity>=1,"credit redemption guarantees minimum rarity");reward.Delete();
  var bonded=new Horse();bonded.SetControlMaster(p);bonded.IsBonded=true;bonded.Name="Book test pet";bonded.Skills.Wrestling.Base=111;bonded.MoveToWorld(p.Location,p.Map);var bondedTicket=HavenPetTicket.Store(bonded,p,p.Backpack);check(bondedTicket!=null&&bondedTicket.Parent is HavenPetBook&&bonded.IsBonded,"bonded shrink routes to book and preserves bond");check(!HavenPetExchange.Exchange(p,bondedTicket)&&!bondedTicket.Deleted,"bonded book pet cannot be exchanged");check(bondedTicket.Claim(p)&&bonded.ControlMaster==p&&bonded.IsBonded&&bonded.Name=="Book test pet"&&bonded.Skills.Wrestling.Base==111,"book releases exact bonded pet with progress");bonded.Delete();var sanctuary=HavenPetBook.Ensure(p);var addTicket=new HavenPetTicket(p,0);p.Backpack.DropItem(addTicket);sanctuary.BeginAdd(p);p.Target.Invoke(p,addTicket);check(addTicket.Parent==sanctuary&&!HavenPetExchange.Eligible(p,addTicket),"targeted unbonded ticket enters protected sanctuary");check(HavenPetExchange.Eligible(p,addTicket,sanctuary),"book explicitly allows eligible exchange");addTicket.Favorite=true;check(!HavenPetExchange.Exchange(p,addTicket,sanctuary)&&!addTicket.Deleted,"favorite blocks book exchange");addTicket.Favorite=false;addTicket.Pet.IsBonded=true;check(!HavenPetExchange.Exchange(p,addTicket,sanctuary),"bonded blocks explicit book exchange");addTicket.Pet.IsBonded=false;var beforeCredits=HavenPetExchange.Balance(p);check(HavenPetExchange.Exchange(p,addTicket,sanctuary)&&HavenPetExchange.Balance(p)==beforeCredits+1,"book exchange consumes ticket and credits once");check(!HavenPetExchange.Exchange(p,addTicket,sanctuary),"book exchange cannot replay");
  var sortA=new HavenPetTicket(p,0);sortA.Pet.Name="Alpha";sortA.AcquiredAt=DateTime.UtcNow.AddDays(-1);sanctuary.DropItem(sortA);var sortB=new HavenPetTicket(p,0);sortB.Pet.Name="Bravo";sortB.Favorite=true;sanctuary.DropItem(sortB);var field=typeof(PetBookGump).GetField("_tickets",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic);check(((HavenPetTicket[])field.GetValue(new PetBookGump(sanctuary,0)))[0]==sortB,"recent sort puts newest pet first");check(Array.IndexOf((HavenPetTicket[])field.GetValue(new PetBookGump(sanctuary,0,2)),sortA)<Array.IndexOf((HavenPetTicket[])field.GetValue(new PetBookGump(sanctuary,0,2)),sortB),"name sort alphabetical");check(((HavenPetTicket[])field.GetValue(new PetBookGump(sanctuary,0,0,0,"brav"))).Single()==sortB,"pet search ignores case and filters names");check(((HavenPetTicket[])field.GetValue(new PetBookGump(sanctuary,0,0,1))).Single()==sortB,"favorite view filters pets");sortA.Delete();sortB.Delete();
  var ordinary=new Horse();ordinary.SetControlMaster(p);ordinary.MoveToWorld(p.Location,p.Map);var stored=HavenPetTicket.Store(ordinary,p,p.Backpack);check(stored!=null&&HavenPetExchange.Eligible(p,stored)&&HavenPetExchange.Exchange(p,stored),"stored ordinary pet exchanges once");stored.Delete();var legendary=new HavenPetTicket(p,6,5,3);p.Backpack.DropItem(legendary);check(!HavenPetExchange.Eligible(p,legendary)&&!HavenPetExchange.Exchange(p,legendary)&&!legendary.Deleted,"legendary tickets protected from turn-in");var roll=legendary.Pet.Backpack.FindItemByType(typeof(HavenLegendaryPetSkills),true) as HavenLegendaryPetSkills;check(roll!=null&&roll.Boosted.Count()>=3&&roll.Boosted.Count()<=5,"legendary has three to five skills");legendary.Delete();
  var categoryPet=new HavenMoonfang();
  for(int cat=4;cat<8;cat++){var options=HavenPetTrainingMenu.Options(categoryPet,cat);check(options.All(t=>cat==4?t.TrainPoint is MagicalAbility:cat==5?t.TrainPoint is SpecialAbility:cat==6?t.TrainPoint is WeaponAbility:t.TrainPoint is AreaEffect),"ability category contains only its native type "+cat);}categoryPet.Delete();
  foreach(int group in Enumerable.Range(0,5))check(HavenSupplyShops.Catalogs[2].Any(e=>e.Group==group),"reward category has catalog entries "+group);
  var screen=new HavenSupplyShopGump(p,2,0,group:4);check(screen.Entries.OfType<Server.Gumps.GumpButton>().Any(b=>b.ButtonID==1),"grouped shop includes purchase action");screen.OnServerClose(null);
  for(int category=0;category<HavenPetTrainingMenu.Categories.Length;category++){var training=new HavenPetTrainingGump(c,category);check(training.Entries.Count>0,"training category renders "+category);}
 }
}
