"""Generate the in-game chapters and Markdown from one reviewed player guide."""
import html
import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]
topics = json.loads((root / 'docs/player-guide.json').read_text(encoding='utf-8'))
assert len(topics) <= 18 and len({t['title'] for t in topics}) == len(topics)
source = ['// Generated by tools/build_player_guide.py from docs/player-guide.json.',
          'namespace Server.UOOffline;', '', 'public static partial class HavenFieldGuide', '{',
          '    internal readonly record struct Topic(string Title, string Text, string Html);',
          '    internal static readonly Topic[] Topics =', '    [']
markdown = ['# Haven Field Guide', '', 'Open in game with `[guide`, `[havenhelp` or `[wiki`.', '',
            'Use the chapter list or search; the **Free book** button provides a reusable copy.', '']
for topic in topics:
    title, text = topic['title'], topic['text']
    lines = []
    for line in text.splitlines():
        lines.append('<b>' + html.escape(line[3:]) + '</b>' if line.startswith('## ') else html.escape(line))
    body = '<basefont color=#181818>' + '<br>'.join(lines) + '</basefont>'
    source.append('        new(' + ', '.join(json.dumps(s, ensure_ascii=True) for s in (title, text, body)) + '),')
    markdown.extend(['## ' + title, '', text.replace('## ', '### '), ''])
source.extend(['    ];', '}', ''])
(root / 'playerbots/source/CustomBots/UOOffline/HavenFieldGuideContent.cs').write_text('\n'.join(source), encoding='utf-8')
(root / 'docs/PLAYER-GUIDE.md').write_text('\n'.join(markdown), encoding='utf-8')
print(f'Generated {len(topics)} matching in-game and Markdown chapters.')
